apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017

---
apiVersion: v1
kind: Endpoints
metadata:
  name: mongodb
subsets:
  - addresses:
      - ip: 10.0.1.1
    ports:
      - port: 27017
        name: mongodb
