### Home route
GET http://localhost:3000/


### Info Route
GET http://localhost:3000/users/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MTQwMTE5MDgsImV4cCI6MTYxNDAxMjIwOCwiYXVkIjoiNjAzM2QwZjE4MDI5NzQ3NWIxMDc5YjU3IiwiaXNzIjoidGVzdC5jb20ifQ.n-aItFYaPTm436eOHBrFuLWI-WepkMzdMNScZd-IGtE

### Login Route 
POST http://localhost:3000/users/auth/login
Content-Type: application/json

{
    "username" : "user_123",
    "password": "password"
}

### Register Route
POST http://localhost:3000/users/auth/register
Content-Type: application/json

{
    "username" : "user_123",
    "password": "password"
    
}

### Refresh token Route
POST http://localhost:3000/users/auth/refresh-token
Content-Type: application/json

{
    "refreshToken" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MTQwMTE5MDgsImV4cCI6MTY0NTU2OTUwOCwiYXVkIjoiNjAzM2QwZjE4MDI5NzQ3NWIxMDc5YjU3IiwiaXNzIjoidGVzdC5jb20ifQ.QJ8EJ-r-oNUOaxo20b1R6F8ijjL36Vp79EU0fg6qzNM"
}

### Logout Route
DELETE http://localhost:3000/users/auth/logout
Content-Type: application/json

{
    "refreshToken" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MTQwMTE5MDgsImV4cCI6MTY0NTU2OTUwOCwiYXVkIjoiNjAzM2QwZjE4MDI5NzQ3NWIxMDc5YjU3IiwiaXNzIjoidGVzdC5jb20ifQ.QJ8EJ-r-oNUOaxo20b1R6F8ijjL36Vp79EU0fg6qzNM"
}
