### Home route
GET http://localhost:3000/


### Login Route
POST http://localhost:3000/user/login
Content-Type: application/json

{
    "username" : "user123",
    "password": "password",
    "isAdmin": true
}

### Register Route
POST http://localhost:3000/user/register
Content-Type: application/json

{
    "username" : "user_123",
    "password": "password",
    "isAdmin": true
}

### Refresh token Route
POST http://localhost:3000/user/refresh-token


### Logout Route
DELETE http://localhost:3000/user/logout