@baseUrl = http://localhost:3000

### Home route
GET {{baseUrl}}

###

# @name login
POST {{baseUrl}}/users/auth/login
Content-Type: application/json

{
    "username" : "admin",
    "password": "password"
}

###

@refreshToken = {{login.response.body.$.refreshToken}}
@accessToken = {{login.response.body.$.accessToken}}


# @name register
POST {{baseUrl}}/users/auth/register
Content-Type: application/json

{
    "username" : "user_",
    "password": "password"
    
}

###

# @name refresh
POST {{baseUrl}}/users/auth/refresh-token
Content-Type: application/json

{
    "refreshToken" : "{{refreshToken}}"
}

###
@accessToken = {{refresh.response.body.$.accessToken}}


# @name logout
DELETE {{baseUrl}}/users/auth/logout
Content-Type: application/json

{
    "refreshToken" : "{{refreshToken}}"
}

###

# @name userInfo
GET {{baseUrl}}/users/
Authorization: Bearer {{accessToken}}

###

# @name userInfoAll
GET {{baseUrl}}/users/all/
Authorization: Bearer {{accessToken}}

### 

# @name userInfoID
GET {{baseUrl}}/users/6033e6d878211f0052c85d98
Authorization: Bearer {{accessToken}}

### 

# @name createUser
POST {{baseUrl}}/users
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "username" : "user_123",
    "password": "password"
    
}

### 

# @name updateUser
PUT {{baseUrl}}/users
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "username" : "admin"
}

### 

# @name updateUserID
PUT {{baseUrl}}/users/603400751f9551b6966e40c1
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "isAdmin": "true"
}