apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: usernode
spec:
  replicas: 1
  selector:
    matchLabels:
      name: usernode
  template:
    metadata:
      name: usernode
      labels:
        name: usernode
    spec:
      containers:
        - name: usernode
          image: usernode_app
          imagePullPolicy: Never
          ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: usernode-service
spec:
  type: NodePort
  selector:
    name: usernode
  ports:
    - port: 3000
      targetPort: 3000
