apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: authnode
spec:
  replicas: 1
  selector:
    matchLabels:
      name: authnode
  template:
    metadata:
      name: authnode
      labels:
        name: authnode
    spec:
      containers:
        - name: authnode
          image: authnode_app
          imagePullPolicy: Never
          ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: authnode-service
spec:
  type: NodePort
  selector:
    name: authnode
  ports:
    - port: 3000
      targetPort: 3000
